"""
PowerSense AI — Intelligent Electricity Management Assistant
--------------------------------------------------------------
A Streamlit dashboard implementing:
  1. Home dashboard with KPI cards
  2. Sidebar navigation across all feature areas
  3. Bill Analyzer (upload -> real PDF text extraction -> analysis)
  4. Consumption analytics (trend chart, peak usage, cost)
  5. Multi-agent architecture visualization
  6. AI Assistant chat, RAG-grounded
  7. Confidence / evidence blocks (computed, not hardcoded)
  8. RAG "Knowledge Center" — real TF-IDF retrieval, PDFs can be added live
  9. Savings Simulator
  10. Anomaly / problem detection with severity levels

WHAT'S REAL VS. STILL SIMULATED (read this before a demo)
--------------------------------------------------------
REAL now:
  - RAG: the Knowledge Center articles are chunked and indexed with TF-IDF
    (scikit-learn). The AI Assistant, "why is my bill high", and Problem
    Detection's "possible causes" all retrieve actual top-matching chunks
    via cosine similarity from the SAME index — not separate fixed lists
    that could silently disagree with each other. Upload your own PDFs
    from the Knowledge Center page and test retrieval live.
  - Bill upload: PDFs are read with pypdf and parsed with regex for
    consumer ID / units / total / readings / due date. Found fields are
    used as-is; anything not found falls back to demo data, and the UI
    says explicitly which happened.
  - Confidence score: a z-score of this month's units against historical
    mean/std, not a hardcoded number.
  - Agent Status (sidebar + dashboard): reflects whether each capability
    actually works in this environment (e.g. RAG turns red if
    scikit-learn isn't installed) instead of a constant green.
  - Tariff rate: editable in Settings and actually flows through every
    calculation in the app — it's no longer a display-only input next to
    a hardcoded constant.
  - Recommendations: savings scale with the household's own current usage
    (% of their real units) instead of being an identical fixed list for
    every user.
  - Dashboard "Analyze Bill" / "Ask AI" buttons and the "Issues Detected"
    KPI: wired to real navigation and to the same health/anomaly
    functions the dedicated pages use, instead of doing nothing / showing
    a fixed "2".
  - Hourly usage curve: generated from the household's own monthly units
    via a simple day-shape model, and "Peak Usage Window" is computed
    from that curve — not two independent hardcoded values that could
    contradict each other.
  - Optional live LLM: if you set a Groq API key in Settings (or the
    GROQ_API_KEY env var), chat answers are generated by a real model
    call using retrieved chunks + bill data as context. Without a key,
    answers are assembled directly from the retrieved text instead.

STILL SIMULATED / SIMPLIFIED (be upfront about these — they're labeled in
the UI wherever they appear, not hidden):
  - No OCR — scanned/image bills aren't parsed, only text-based PDFs.
  - The 12-month consumption history is a synthetic series (fixed random
    seed) with no persistent per-user store; it resets every session.
    This is now labeled "Simulated data" directly on the Consumption page
    rather than presented as if it were real meter history.
  - The hourly load curve is a modeled shape scaled to real monthly
    units, not measured interval data — labeled as such in its heading.
  - The tariff model is a single flat Rs./unit rate, not a real
    multi-slab schedule with domestic/commercial categories.
  - Removed outright rather than faked: the Settings page no longer has
    Language/Currency selectors or alert toggles that didn't do anything —
    only the one control that actually affects the app (tariff rate)
    remains.
  - Each "agent" is still a Python function, not an autonomous tool-using
    agent with its own reasoning loop — the Agent Status caption says so.

Run with:
    pip install -r requirements.txt
    streamlit run app.py
"""

import io
import os
import random
import re
from datetime import datetime, timedelta

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import streamlit as st

# Optional dependencies — the app degrades gracefully (with a visible
# warning) instead of crashing if any of these aren't installed.
try:
    from pypdf import PdfReader
    PYPDF_AVAILABLE = True
except ImportError:
    PYPDF_AVAILABLE = False

try:
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.metrics.pairwise import cosine_similarity
    SKLEARN_AVAILABLE = True
except ImportError:
    SKLEARN_AVAILABLE = False

try:
    from groq import Groq
    GROQ_AVAILABLE = True
except ImportError:
    GROQ_AVAILABLE = False

# ----------------------------------------------------------------------
# PAGE CONFIG & GLOBAL STYLE
# ----------------------------------------------------------------------

st.set_page_config(
    page_title="PowerSense AI",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="expanded",
)

CUSTOM_CSS = """
<style>
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}

    .ps-header {
        padding: 0.25rem 0 1rem 0;
        border-bottom: 1px solid rgba(120,120,120,0.2);
        margin-bottom: 1.5rem;
    }
    .ps-title { font-size: 1.9rem; font-weight: 700; margin-bottom: 0; }
    .ps-subtitle { color: #8a8f98; font-size: 0.95rem; margin-top: -6px; }

    .kpi-card {
        background: linear-gradient(135deg, rgba(99,102,241,0.08), rgba(16,185,129,0.06));
        border: 1px solid rgba(120,120,120,0.15);
        border-radius: 14px;
        padding: 1rem 1.1rem;
        height: 100%;
    }
    .kpi-label { font-size: 0.8rem; color: #8a8f98; margin-bottom: 4px; }
    .kpi-value { font-size: 1.5rem; font-weight: 700; }
    .kpi-delta-up { color: #ef4444; font-size: 0.82rem; }
    .kpi-delta-down { color: #10b981; font-size: 0.82rem; }

    .badge {
        display: inline-block;
        padding: 2px 10px;
        border-radius: 999px;
        font-size: 0.78rem;
        font-weight: 600;
    }
    .badge-green  { background: rgba(16,185,129,0.15); color: #10b981; }
    .badge-yellow { background: rgba(234,179,8,0.15);  color: #ca8a04; }
    .badge-orange { background: rgba(249,115,22,0.15); color: #ea580c; }
    .badge-red    { background: rgba(239,68,68,0.15);  color: #ef4444; }

    .agent-box {
        border: 1px solid rgba(120,120,120,0.2);
        border-radius: 12px;
        padding: 0.7rem 0.9rem;
        text-align: center;
        font-size: 0.85rem;
        font-weight: 600;
    }
    .evidence-box {
        background: rgba(120,120,120,0.06);
        border-left: 3px solid #6366f1;
        border-radius: 8px;
        padding: 0.7rem 0.9rem;
        font-size: 0.88rem;
    }
    .source-chip {
        display: inline-block;
        background: rgba(99,102,241,0.1);
        color: #6366f1;
        padding: 3px 10px;
        border-radius: 999px;
        font-size: 0.78rem;
        margin: 2px 4px 2px 0;
    }
    .mode-chip-llm {
        display: inline-block;
        background: rgba(16,185,129,0.12);
        color: #10b981;
        padding: 2px 9px;
        border-radius: 999px;
        font-size: 0.74rem;
        margin-bottom: 6px;
    }
    .mode-chip-retrieval {
        display: inline-block;
        background: rgba(234,179,8,0.12);
        color: #ca8a04;
        padding: 2px 9px;
        border-radius: 999px;
        font-size: 0.74rem;
        margin-bottom: 6px;
    }
</style>
"""
st.markdown(CUSTOM_CSS, unsafe_allow_html=True)

# ----------------------------------------------------------------------
# MOCK CONSUMPTION DATA (still synthetic — see note at top of file)
# ----------------------------------------------------------------------

random.seed(7)
np.random.seed(7)

MONTHS = pd.date_range(end=datetime.today(), periods=12, freq="MS").strftime("%b %Y")


def _mock_consumption_series():
    base = 260
    trend = np.linspace(0, 60, 12)
    noise = np.random.normal(0, 18, 12)
    values = base + trend + noise
    values[-1] = values[-2] * 1.184  # force an 18.4% spike in the latest month
    return np.round(values).astype(int)


if "consumption_df" not in st.session_state:
    st.session_state.consumption_df = pd.DataFrame(
        {"month": MONTHS, "units": _mock_consumption_series()}
    )

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

if "bill_data" not in st.session_state:
    st.session_state.bill_data = None

if "custom_kb_chunks" not in st.session_state:
    st.session_state.custom_kb_chunks = []

if "uploaded_kb_files" not in st.session_state:
    st.session_state.uploaded_kb_files = []

if "groq_api_key" not in st.session_state:
    st.session_state.groq_api_key = ""

if "llm_model" not in st.session_state:
    st.session_state.llm_model = "llama-3.3-70b-versatile"

if "rate_per_unit" not in st.session_state:
    st.session_state.rate_per_unit = 42.0  # Rs. per kWh, editable in Settings — real, not decorative

if "nav_page" not in st.session_state:
    st.session_state.nav_page = "🏠 Dashboard"

df = st.session_state.consumption_df
current_units = int(df["units"].iloc[-1])
previous_units = int(df["units"].iloc[-2])
pct_change = round((current_units - previous_units) / previous_units * 100, 1)
RATE_PER_UNIT = st.session_state.rate_per_unit  # actually flows through every calc below
current_bill = int(current_units * RATE_PER_UNIT * 1.08)  # + taxes/FPA
estimated_saving = int(current_units * 0.10 * RATE_PER_UNIT)


# ----------------------------------------------------------------------
# KNOWLEDGE BASE — real article text (this is what actually gets
# chunked + indexed below, not just a list of titles)
# ----------------------------------------------------------------------

KNOWLEDGE_BASE = [
    {
        "title": "Electricity Tariff Slabs Explained",
        "category": "Tariffs",
        "content": (
            "Most residential electricity tariffs are structured in slabs, meaning the "
            "price per unit (kWh) increases as your total monthly consumption crosses "
            "certain thresholds, rather than every unit being billed at a single flat "
            "rate. A household using 150 units might pay a low rate on the first block "
            "and a higher rate only on the units above that block. This is why doubling "
            "your usage from one month to the next often more than doubles your bill — "
            "part of the extra consumption falls into a higher-priced slab. Tariff "
            "categories also differ by connection type: domestic, commercial, and "
            "industrial connections are billed on separate schedules, and domestic "
            "tariffs are usually the lowest per-unit rate up to a protected lifeline "
            "threshold meant to keep basic usage affordable. Because slab boundaries and "
            "rates are revised periodically by the regulator, the exact cutoffs and "
            "prices for your bill can change between billing cycles, so the same unit "
            "count in different months is not guaranteed to cost exactly the same."
        ),
    },
    {
        "title": "Understanding Fuel Price Adjustment (FPA)",
        "category": "Billing",
        "content": (
            "The Fuel Price Adjustment, or FPA, is a variable surcharge (or occasionally "
            "a credit) added to your bill to account for month-to-month swings in the "
            "cost of fuel used to generate electricity, separate from the base tariff "
            "rate. Because generation fuel costs fluctuate with international oil and "
            "gas prices, currency exchange rates, and the generation mix used in a given "
            "month, the FPA line item can vary noticeably even if your own consumption "
            "stays flat. A month with a higher share of expensive thermal generation "
            "typically produces a higher FPA charge, while a month leaning more on "
            "cheaper hydro or other lower-cost sources can produce a lower FPA charge or "
            "even a rebate. This is why two bills with the same number of units consumed "
            "can still show a different total amount — the difference often lives in the "
            "FPA line rather than in your actual usage."
        ),
    },
    {
        "title": "How Billing Cycles & Due Dates Work",
        "category": "Billing",
        "content": (
            "A billing cycle is the period between two meter readings, typically about "
            "30 days, during which your consumption is measured and then converted into "
            "a bill. The bill is usually issued a few days after the reading is taken, "
            "and it specifies a due date — commonly around two weeks after issue — by "
            "which payment must be made to avoid a late payment surcharge or, in "
            "prolonged non-payment cases, disconnection. If a meter reading is missed or "
            "inaccessible, some utilities issue an estimated bill based on your recent "
            "consumption history, which is then corrected (with a credit or additional "
            "charge) once an actual reading is taken. Keeping track of your billing date "
            "and due date each month is the simplest way to avoid surcharges that have "
            "nothing to do with how much electricity you actually used."
        ),
    },
    {
        "title": "Common Reasons for Sudden Bill Increases",
        "category": "Troubleshooting",
        "content": (
            "A sudden jump in your bill usually traces back to one of a few causes. The "
            "most common is a genuine increase in consumption — longer air conditioner "
            "or heater runtime, a new appliance, more people at home, or a shift in "
            "weather that changes how long cooling or heating equipment runs each day. "
            "The second common cause is tariff-slab crossing: even a modest increase in "
            "units can push part of your usage into a higher-priced slab, so the bill "
            "rises faster than the unit count did. Third, the FPA surcharge can move "
            "independently of your own usage and account for part of an increase you "
            "didn't cause. Less commonly, a meter fault, a misread meter, or a billing "
            "error can inflate a bill — comparing the current and previous meter "
            "readings printed on the bill against your own meter is the fastest way to "
            "rule this out. Consumption also naturally rises during peak summer or "
            "winter months purely from seasonal appliance use."
        ),
    },
    {
        "title": "Energy-Saving Tips for Air Conditioners",
        "category": "Conservation",
        "content": (
            "Air conditioners are typically the single largest contributor to a "
            "household's summer electricity bill, so small changes here have an "
            "outsized effect. Setting the thermostat a few degrees higher (around "
            "24-26°C rather than 18-20°C) can meaningfully cut consumption without a "
            "large comfort trade-off, since each degree of extra cooling demands "
            "disproportionately more energy. Running the AC on a timer or turning it off "
            "during the coolest overnight hours, keeping doors and windows sealed while "
            "it runs, cleaning or replacing filters regularly so the compressor isn't "
            "working against restricted airflow, and shading windows that get direct "
            "afternoon sun all reduce the load. Shifting AC-heavy hours outside a utility's "
            "peak pricing window (commonly early evening) can also reduce cost even if "
            "total runtime doesn't change much, when time-of-use rates apply."
        ),
    },
    {
        "title": "How to Read Your Electricity Meter",
        "category": "Guides",
        "content": (
            "For a standard digital meter, the consumption figure you need is usually "
            "the cumulative kWh reading shown on the main display, sometimes cycling "
            "with other values like voltage or current if the meter rotates through "
            "screens automatically. To calculate your own usage between two dates, "
            "subtract the earlier reading from the later reading; the result should be "
            "close to the 'units consumed' figure printed on your bill. A large "
            "mismatch between your own reading and the bill's reading is worth reporting "
            "to the utility, since it can indicate a misread, a transcription error, or "
            "an estimated (rather than actual) bill. Smart or net meters may show "
            "additional values such as time-of-use blocks or exported units if you have "
            "solar generation, which are broken out separately from ordinary imported "
            "consumption."
        ),
    },
]


# ----------------------------------------------------------------------
# RAG: chunking, indexing (TF-IDF), and retrieval
# ----------------------------------------------------------------------

def _split_sentences(text):
    sentences = re.split(r"(?<=[.!?])\s+", text.strip())
    return [s.strip() for s in sentences if s.strip()]


def _chunk_text(text, sentences_per_chunk=3):
    """Groups sentences into small overlap-free chunks for indexing."""
    sents = _split_sentences(text)
    chunks = []
    for i in range(0, len(sents), sentences_per_chunk):
        chunk = " ".join(sents[i:i + sentences_per_chunk])
        if chunk:
            chunks.append(chunk)
    return chunks


def build_base_chunks():
    chunks = []
    for article in KNOWLEDGE_BASE:
        for c in _chunk_text(article["content"]):
            chunks.append({"title": article["title"], "category": article["category"], "text": c})
    return chunks


def extract_text_from_pdf(uploaded_file):
    """Real text extraction via pypdf. Returns '' (not an exception) for
    scanned/image-only PDFs or unreadable files, so callers can show an
    honest message instead of guessing."""
    if not PYPDF_AVAILABLE or uploaded_file is None:
        return ""
    try:
        reader = PdfReader(io.BytesIO(uploaded_file.getvalue()))
        return "\n".join(page.extract_text() or "" for page in reader.pages)
    except Exception:
        return ""


def get_rag_index():
    """Builds (and session-caches) a TF-IDF index over the built-in
    Knowledge Base articles plus any PDFs uploaded during this session.
    Rebuilds only when the set of custom chunks changes."""
    custom_chunks = st.session_state.get("custom_kb_chunks", [])
    version_key = f"base+{len(custom_chunks)}"

    cached = st.session_state.get("rag_index")
    if cached is not None and st.session_state.get("rag_index_version") == version_key:
        return cached

    chunks = build_base_chunks() + custom_chunks
    if not chunks or not SKLEARN_AVAILABLE:
        index = (None, None, chunks)
    else:
        texts = [c["text"] for c in chunks]
        vectorizer = TfidfVectorizer(stop_words="english", ngram_range=(1, 2))
        matrix = vectorizer.fit_transform(texts)
        index = (vectorizer, matrix, chunks)

    st.session_state.rag_index = index
    st.session_state.rag_index_version = version_key
    return index


def rag_search(query, k=3, min_score=0.06):
    """Real cosine-similarity retrieval over the TF-IDF index. Returns only
    chunks above min_score, so an off-topic question can legitimately
    return zero sources instead of always citing something."""
    vectorizer, matrix, chunks = get_rag_index()
    if vectorizer is None or matrix is None or not chunks:
        return []
    q_vec = vectorizer.transform([query])
    sims = cosine_similarity(q_vec, matrix).flatten()
    ranked = sims.argsort()[::-1][:k]
    results = []
    for i in ranked:
        if sims[i] >= min_score:
            item = dict(chunks[i])
            item["score"] = round(float(sims[i]), 3)
            results.append(item)
    return results


# ----------------------------------------------------------------------
# --- AI HOOK --- functions
# ----------------------------------------------------------------------

def parse_bill_text(text):
    """Best-effort regex extraction from raw bill text. Returns only the
    fields it can confidently find; anything not matched is left out so
    the caller can fall back to demo data for just that field."""
    patterns = {
        "consumer_id": r"(?:consumer\s*(?:id|no\.?|number)|reference\s*(?:no\.?|number))[:\s#-]*([A-Za-z0-9\-]{5,20})",
        "units_consumed": r"(?:units\s*consumed|total\s*units)[:\s]*([\d,]+)",
        "total_payable": r"(?:total\s*(?:payable|amount|bill)|amount\s*due)[:\s]*(?:rs\.?)?\s*([\d,]+)",
        "previous_reading": r"previous\s*reading[:\s]*([\d,]+)",
        "current_reading": r"current\s*reading[:\s]*([\d,]+)",
        "due_date": r"due\s*date[:\s]*([\d]{1,2}[-/\s][A-Za-z0-9]{2,10}[-/\s][\d]{2,4})",
    }
    found = {}
    for key, pat in patterns.items():
        m = re.search(pat, text, re.IGNORECASE)
        if m:
            found[key] = m.group(1).replace(",", "")
    return found


def ai_extract_bill(uploaded_file):
    """Bill Extraction Agent.
    For real PDF uploads: extracts text with pypdf and parses it with
    regex. Fields it finds are used as-is; fields it can't find fall back
    to the demo dataset, and the UI is told which case happened so it can
    say so honestly instead of silently pretending everything was parsed.
    """
    parsed = {}
    parse_status = "demo"

    if uploaded_file is not None:
        file_type = getattr(uploaded_file, "type", "") or ""
        if "pdf" in file_type:
            raw_text = extract_text_from_pdf(uploaded_file)
            if raw_text.strip():
                parsed = parse_bill_text(raw_text)
                parse_status = "parsed" if len(parsed) >= 3 else "partial"
            else:
                parse_status = "unreadable"
        else:
            parse_status = "image_no_ocr"

    base = {
        "consumer_id": "10-2938-4471",
        "billing_month": datetime.today().strftime("%B %Y"),
        "previous_reading": 18420,
        "current_reading": 18420 + current_units,
        "units_consumed": current_units,
        "electricity_charges": int(current_units * RATE_PER_UNIT),
        "taxes": int(current_units * RATE_PER_UNIT * 0.06),
        "fpa_adjustment": int(current_units * RATE_PER_UNIT * 0.02),
        "total_payable": current_bill,
        "due_date": (datetime.today() + timedelta(days=14)).strftime("%d %b %Y"),
    }

    for key in ["consumer_id", "previous_reading", "current_reading", "units_consumed", "total_payable", "due_date"]:
        if key in parsed:
            if key in ("consumer_id", "due_date"):
                base[key] = parsed[key]
            else:
                try:
                    base[key] = int(parsed[key])
                except ValueError:
                    pass

    if "units_consumed" in parsed:
        try:
            u = int(parsed["units_consumed"])
            base["electricity_charges"] = int(u * RATE_PER_UNIT)
            base["taxes"] = int(u * RATE_PER_UNIT * 0.06)
            base["fpa_adjustment"] = int(u * RATE_PER_UNIT * 0.02)
            if "total_payable" not in parsed:
                base["total_payable"] = int(u * RATE_PER_UNIT * 1.08)
        except ValueError:
            pass

    base["_parse_status"] = parse_status
    base["_fields_found"] = list(parsed.keys())
    return base


def compute_confidence(units_now, history_series):
    """Confidence for the bill-health/anomaly call, derived from a z-score
    of this month's units against the historical mean/std — not a fixed
    number. Returns (confidence_pct, z_score)."""
    hist = history_series.iloc[:-1] if len(history_series) > 1 else history_series
    mean_h = hist.mean()
    std_h = hist.std()
    if not std_h or np.isnan(std_h) or std_h == 0:
        return 60.0, 0.0
    z = abs(units_now - mean_h) / std_h
    confidence = round(min(99.0, 100 * (1 - np.exp(-z / 2))), 1)
    return confidence, round(float(z), 2)


def ai_bill_health(units_now, units_prev):
    """Bill Analysis Agent."""
    change = (units_now - units_prev) / units_prev * 100
    if change > 15:
        return "Needs Attention", "🔴", change
    elif change > 8:
        return "Watch", "🟡", change
    return "Normal", "🟢", change


def ai_why_bill_high(units_now, units_prev):
    """Consumption reasoning agent. The headline percentage is a real
    calculation; the contributing factors are whatever the RAG index
    actually retrieves for a 'why did my bill increase' query, so they
    change if you add or remove Knowledge Center content."""
    change = round((units_now - units_prev) / units_prev * 100, 1)
    retrieved = rag_search(
        "reasons electricity bill increased tariff slab peak hours FPA", k=3, min_score=0.02
    )
    if retrieved:
        contributors = [r["text"] for r in retrieved]
        contributor_sources = [r["title"] for r in retrieved]
    else:
        contributors = ["Higher total consumption this billing period drove the increase."]
        contributor_sources = []
    return change, contributors, contributor_sources


def ai_detect_anomaly(units_now, avg_units):
    """Problem Detection Agent. Severity is real math on real (if synthetic)
    numbers. Causes are pulled from the same RAG index used everywhere else
    in the app, instead of a second, separate hardcoded list that could
    silently drift from the Knowledge Center content."""
    diff_pct = round((units_now - avg_units) / avg_units * 100, 1)
    if diff_pct > 20:
        severity, badge = "High", "badge-red"
    elif diff_pct > 10:
        severity, badge = "Medium", "badge-orange"
    elif diff_pct > 3:
        severity, badge = "Low", "badge-yellow"
    else:
        severity, badge = "None", "badge-green"

    retrieved = rag_search(
        "possible causes unusual electricity consumption spike appliance", k=3, min_score=0.02
    )
    if retrieved:
        causes = [r["text"] for r in retrieved]
        cause_sources = [r["title"] for r in retrieved]
    else:
        causes = ["Not enough indexed knowledge to explain this — add a relevant article or PDF."]
        cause_sources = []
    return diff_pct, severity, badge, causes, cause_sources


def ai_recommendations(units_now):
    """Recommendation Agent. Impact figures scale with the household's own
    current usage (as a % of their real units) instead of fixed absolute
    numbers that were identical for every user regardless of their
    consumption level."""
    plan = [
        {"title": "Shift AC usage outside peak hours (7–11 PM)", "unit_pct": 0.095},
        {"title": "Reduce AC runtime by 1 hour/day", "unit_pct": 0.07},
        {"title": "Switch to LED lighting in remaining fixtures", "unit_pct": 0.03},
        {"title": "Service or inspect appliances older than 8 years", "unit_pct": 0.045},
    ]
    recs = []
    for item in plan:
        units = max(1, round(units_now * item["unit_pct"]))
        recs.append({
            "title": item["title"],
            "impact": f"~{units} units/month ({item['unit_pct']*100:.0f}% of your usage)",
            "saving": f"Rs. {int(units * RATE_PER_UNIT):,}",
        })
    return recs


def index_pdf_into_rag(uploaded_file, raw_text, label):
    """Chunks freshly-extracted PDF text and adds it to the session's RAG
    index (same TF-IDF index the AI Assistant and suggestions draw from),
    so an uploaded bill or document is immediately searchable — not just
    regex-parsed for a handful of fields."""
    if not raw_text or not raw_text.strip():
        return False
    already = any(c.get("_source_file") == uploaded_file.name for c in st.session_state.custom_kb_chunks)
    if already:
        return True
    new_chunks = [
        {"title": label, "category": "Your Documents", "text": c, "_source_file": uploaded_file.name}
        for c in _chunk_text(raw_text)
    ]
    st.session_state.custom_kb_chunks.extend(new_chunks)
    return True


def _secret_groq_key():
    """Checks st.secrets (Streamlit Cloud's standard secret store) without
    raising if no secrets.toml exists locally."""
    try:
        return st.secrets.get("GROQ_API_KEY", "")
    except Exception:
        return ""


def get_groq_client():
    api_key = (
        st.session_state.get("groq_api_key")
        or os.environ.get("GROQ_API_KEY")
        or _secret_groq_key()
    )
    if not api_key or not GROQ_AVAILABLE:
        return None
    try:
        return Groq(api_key=api_key)
    except Exception:
        return None


def ai_chat_response(user_message):
    """Chat Agent, backed by real retrieval (TF-IDF over the Knowledge
    Center articles + any uploaded PDFs). If a Groq API key is set
    (Settings page, or GROQ_API_KEY env var), the retrieved chunks
    and bill data are sent to a real model call to generate the answer.
    Without a key, the answer is assembled directly from the retrieved
    text — still real retrieval, just no generative paraphrase step.
    Returns (text, sources, mode) where mode is 'llm' or 'retrieval'."""
    retrieved = rag_search(user_message, k=3)
    bill_facts = (
        f"Current month: {current_units} kWh, Rs. {current_bill:,}. "
        f"Previous month: {previous_units} kWh. Change: {pct_change:+.1f}%."
    )

    client = get_groq_client()
    if client is not None:
        context_block = "\n\n".join(f"Source: {r['title']}\n{r['text']}" for r in retrieved) \
            or "No matching knowledge base passages were retrieved for this question."
        try:
            resp = client.chat.completions.create(
                model=st.session_state.get("llm_model", "llama-3.3-70b-versatile"),
                max_tokens=400,
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are PowerSense AI, an assistant inside a household electricity "
                            "dashboard. Answer the user's question using ONLY the bill data and "
                            "knowledge-base context provided below. Be concise (3-5 sentences). "
                            "If the context doesn't actually cover the question, say so plainly "
                            "instead of guessing or inventing numbers."
                        ),
                    },
                    {
                        "role": "user",
                        "content": f"Bill data:\n{bill_facts}\n\nKnowledge base context:\n{context_block}\n\nQuestion: {user_message}",
                    },
                ],
            )
            text = (resp.choices[0].message.content or "").strip()
            if text:
                sources = [r["title"] for r in retrieved]
                return text, sources, "llm"
        except Exception as e:
            st.session_state["_last_llm_error"] = str(e)

    # Retrieval-only fallback (no key configured, or the API call failed)
    if retrieved:
        lead = retrieved[0]
        text = f"From **{lead['title']}**: {lead['text']}"
        if len(retrieved) > 1:
            text += f"\n\nAlso relevant — **{retrieved[1]['title']}**: {retrieved[1]['text']}"
        text += f"\n\n_Your numbers: {bill_facts}_"
        sources = [r["title"] for r in retrieved]
    else:
        text = (
            "I couldn't find anything in the Knowledge Center relevant to that. Try asking "
            "about tariff slabs, the FPA, billing cycles, sudden bill increases, AC energy "
            "saving, or how to read your meter — or add a PDF in the Knowledge Center page."
        )
        sources = []
    return text, sources, "retrieval"


def ai_llm_savings_suggestions(bill_data, rule_based_recs):
    """Generates a personalized, LLM-written savings plan via Groq, grounded
    in the user's actual bill data plus whatever the RAG index retrieves —
    including any uploaded bill/document PDFs, not just the built-in
    Knowledge Center. Falls back to None if no key is configured or the
    call fails, so the caller can show the rule-based plan instead."""
    client = get_groq_client()
    if client is None:
        return None

    retrieved = rag_search(
        "reduce electricity bill save energy tips appliances peak hours", k=4, min_score=0.0
    )
    context_block = "\n\n".join(f"Source: {r['title']}\n{r['text']}" for r in retrieved) \
        or "No specific knowledge-base passages retrieved."
    rule_lines = "\n".join(f"- {r['title']}: {r['impact']}, est. saving {r['saving']}" for r in rule_based_recs)

    bill_summary = (
        f"Units consumed this month: {bill_data.get('units_consumed', current_units)} kWh. "
        f"Total payable: Rs. {bill_data.get('total_payable', current_bill):,}. "
        f"Previous month units: {previous_units} kWh. Change: {pct_change:+.1f}%. "
        f"Tariff rate in use: Rs. {RATE_PER_UNIT}/kWh."
    )

    try:
        resp = client.chat.completions.create(
            model=st.session_state.get("llm_model", "llama-3.3-70b-versatile"),
            max_tokens=500,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are PowerSense AI's savings advisor. Using ONLY the bill data, "
                        "the baseline calculated recommendations, and the knowledge-base "
                        "context given, write a short, specific, personalized savings plan "
                        "(4-6 bullet points, each one line, each with a rough Rs./month "
                        "impact where sensible). Ground every claim in the data given — do "
                        "not invent appliances or numbers the user hasn't mentioned. End "
                        "with one sentence on the single highest-impact action."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        f"Bill data:\n{bill_summary}\n\n"
                        f"Baseline calculated recommendations:\n{rule_lines}\n\n"
                        f"Knowledge base / uploaded document context:\n{context_block}\n\n"
                        "Write the personalized savings plan."
                    ),
                },
            ],
        )
        text = (resp.choices[0].message.content or "").strip()
        sources = [r["title"] for r in retrieved]
        return (text, sources) if text else None
    except Exception as e:
        st.session_state["_last_llm_error"] = str(e)
        return None


# ----------------------------------------------------------------------
# SIDEBAR NAVIGATION
# ----------------------------------------------------------------------

with st.sidebar:
    st.markdown("### ⚡ PowerSense AI")
    st.caption("Intelligent electricity management")
    st.divider()

    page = st.radio(
        "Navigate",
        [
            "🏠 Dashboard",
            "🧾 Bill Analyzer",
            "📊 Consumption",
            "🚨 Problem Detection",
            "💡 Recommendations",
            "💰 Savings Simulator",
            "🤖 AI Assistant",
            "📚 Knowledge Center",
            "⚙️ Settings",
        ],
        label_visibility="collapsed",
        key="nav_page",
    )

    st.divider()
    st.markdown("##### Agent Status")
    _n_chunks = len(get_rag_index()[2])
    # Real status: only "green" when the capability it names actually works
    # in this environment, not a decorative constant.
    agent_status = [
        ("Bill Analysis", True, "pure Python + regex, always available"),
        ("Consumption", True, "pure Python, always available"),
        ("Problem Detection", True, "pure Python, always available"),
        ("Recommendation", True, "pure Python, always available"),
        ("RAG Knowledge", SKLEARN_AVAILABLE and _n_chunks > 0,
         f"{_n_chunks} chunks indexed" if SKLEARN_AVAILABLE else "scikit-learn not installed"),
    ]
    agents = [name for name, _, _ in agent_status]
    for name, ok, detail in agent_status:
        dot = "🟢" if ok else "🔴"
        st.markdown(f"{dot} {name} Agent")
    st.caption(
        "RAG Knowledge Agent status reflects whether scikit-learn is installed and the "
        f"index is populated ({_n_chunks} chunks now). The other four are coordinated "
        "functions, not autonomous tool-using agents — no hand-off between them exists yet."
    )

# ----------------------------------------------------------------------
# PAGE: DASHBOARD
# ----------------------------------------------------------------------

if page == "🏠 Dashboard":
    st.markdown(
        '<div class="ps-header"><div class="ps-title">Welcome back 👋</div>'
        '<div class="ps-subtitle">Here\'s your electricity overview</div></div>',
        unsafe_allow_html=True,
    )

    # Real issue count instead of a hardcoded "2" — derived from the same
    # functions the Bill Analyzer / Problem Detection pages actually use.
    _avg_units_dash = int(df["units"].iloc[:-1].mean())
    _health_status, _, _ = ai_bill_health(current_units, previous_units)
    _diff_pct_dash, _severity_dash, _, _, _ = ai_detect_anomaly(current_units, _avg_units_dash)
    _issues = [s for s in [
        _health_status if _health_status != "Normal" else None,
        _severity_dash if _severity_dash != "None" else None,
    ] if s]
    issues_value = str(len(_issues))
    issues_delta = ", ".join(_issues) if _issues else "None flagged"

    c1, c2, c3, c4, c5 = st.columns(5)
    kpis = [
        (c1, "💰 Current Bill", f"Rs. {current_bill:,}", f"+{pct_change}%", True),
        (c2, "⚡ Units Consumed", f"{current_units} kWh", f"{pct_change:+.1f}%", pct_change > 0),
        (c3, "📈 Consumption Change", f"{pct_change:+.1f}%", "vs last month", pct_change > 0),
        (c4, "🚨 Issues Detected", issues_value, issues_delta, len(_issues) > 0),
        (c5, "💡 Estimated Saving", f"Rs. {estimated_saving:,}", "assumes 10% reduction", False),
    ]
    for col, label, value, delta, is_up in kpis:
        with col:
            delta_class = "kpi-delta-up" if is_up else "kpi-delta-down"
            st.markdown(
                f'<div class="kpi-card"><div class="kpi-label">{label}</div>'
                f'<div class="kpi-value">{value}</div>'
                f'<div class="{delta_class}">{delta}</div></div>',
                unsafe_allow_html=True,
            )

    st.write("")
    left, right = st.columns([2, 1])

    with left:
        st.markdown("#### 📈 Consumption Trend")
        fig = px.line(df, x="month", y="units", markers=True)
        fig.update_traces(line_color="#6366f1", fill="tozeroy",
                           fillcolor="rgba(99,102,241,0.08)")
        fig.update_layout(height=320, margin=dict(l=10, r=10, t=10, b=10),
                           xaxis_title=None, yaxis_title="Units (kWh)")
        st.plotly_chart(fig, use_container_width=True)

    with right:
        st.markdown("#### 🚨 AI Insights")
        st.markdown(
            f'<div class="evidence-box">⚠️ Consumption increased '
            f'<b>{pct_change:+.1f}%</b> vs last month<br><br>'
            f'💡 Optimizing AC usage could save about '
            f'<b>Rs. {estimated_saving:,}/month</b></div>',
            unsafe_allow_html=True,
        )
        st.write("")
        b1, b2 = st.columns(2)
        with b1:
            if st.button("🧾 Analyze Bill", use_container_width=True):
                st.session_state.nav_page = "🧾 Bill Analyzer"
                st.rerun()
        with b2:
            if st.button("🤖 Ask AI", use_container_width=True):
                st.session_state.nav_page = "🤖 AI Assistant"
                st.rerun()

    st.write("")
    st.markdown("#### 🤖 PowerSense AI Engine")
    cols = st.columns(5)
    for col, (name, ok, detail) in zip(cols, agent_status):
        with col:
            dot = "🟢" if ok else "🔴"
            st.markdown(f'<div class="agent-box">{dot}<br>{name}<br>Agent</div>',
                         unsafe_allow_html=True)
            st.caption(detail)

# ----------------------------------------------------------------------
# PAGE: BILL ANALYZER
# ----------------------------------------------------------------------

elif page == "🧾 Bill Analyzer":
    st.markdown('<div class="ps-title">🧾 Bill Analyzer</div>'
                '<div class="ps-subtitle">Upload your electricity bill for AI extraction & analysis</div>',
                unsafe_allow_html=True)
    st.write("")

    if not PYPDF_AVAILABLE:
        st.warning("`pypdf` isn't installed, so PDF text extraction is disabled and uploads "
                   "will fall back to demo data. Run `pip install pypdf` and restart.")

    uploaded = st.file_uploader("Upload bill (PDF or image)", type=["pdf", "png", "jpg", "jpeg"])

    if uploaded is not None or st.button("Use sample bill for demo"):
        with st.spinner("Reading your bill..."):
            try:
                data = ai_extract_bill(uploaded)
                st.session_state.bill_data = data
                if uploaded is not None and "pdf" in (getattr(uploaded, "type", "") or ""):
                    raw_text = extract_text_from_pdf(uploaded)
                    if index_pdf_into_rag(uploaded, raw_text, f"Your Bill — {uploaded.name}"):
                        st.session_state.pop("rag_index", None)  # force reindex with new chunks
            except Exception as e:
                st.error(f"Couldn't process that file ({e}). Showing demo data instead.")
                st.session_state.bill_data = ai_extract_bill(None)

    if st.session_state.bill_data:
        data = st.session_state.bill_data
        status = data.get("_parse_status", "demo")

        status_messages = {
            "parsed": ("success", "✅ Extracted directly from your uploaded PDF "
                                    f"(fields found: {', '.join(data.get('_fields_found', [])) or 'none'})."),
            "partial": ("warning", "⚠️ Only some fields were found in your PDF "
                                     f"({', '.join(data.get('_fields_found', [])) or 'none'}); the rest are "
                                     "filled from demo data because they weren't in a recognizable format."),
            "unreadable": ("warning", "⚠️ Couldn't extract text from that PDF (it may be a scanned "
                                        "image) — showing demo data instead. OCR isn't implemented yet."),
            "image_no_ocr": ("warning", "⚠️ Image upload received, but OCR isn't implemented yet — "
                                          "showing demo data instead."),
            "demo": ("info", "ℹ️ Showing the sample/demo bill."),
        }
        kind, msg = status_messages.get(status, status_messages["demo"])
        getattr(st, kind)(msg)

        st.markdown("#### Bill Details")
        e1, e2, e3 = st.columns(3)
        with e1:
            st.metric("Consumer ID", data["consumer_id"])
            st.metric("Billing Month", data["billing_month"])
        with e2:
            st.metric("Previous Reading", data["previous_reading"])
            st.metric("Current Reading", data["current_reading"])
        with e3:
            st.metric("Units Consumed", f"{data['units_consumed']} kWh")
            st.metric("Due Date", data["due_date"])

        st.write("")
        cost_df = pd.DataFrame({
            "Component": ["Electricity Charges", "Taxes", "FPA Adjustment"],
            "Amount (Rs.)": [data["electricity_charges"], data["taxes"], data["fpa_adjustment"]],
        })
        c1, c2 = st.columns([1, 1])
        with c1:
            st.dataframe(cost_df, hide_index=True, use_container_width=True)
            st.markdown(f"**Total Payable: Rs. {data['total_payable']:,}**")
        with c2:
            fig = px.pie(cost_df, names="Component", values="Amount (Rs.)", hole=0.55)
            fig.update_layout(height=250, margin=dict(l=10, r=10, t=10, b=10))
            st.plotly_chart(fig, use_container_width=True)

        st.write("")
        st.markdown("#### AI Analysis")
        health_status, emoji, change = ai_bill_health(current_units, previous_units)
        confidence, z_score = compute_confidence(current_units, df["units"])
        badge_class = {"Normal": "badge-green", "Watch": "badge-yellow", "Needs Attention": "badge-red"}[health_status]
        st.markdown(f'<span class="badge {badge_class}">{emoji} Bill Health: {health_status}</span>',
                    unsafe_allow_html=True)
        st.write("")
        st.markdown(
            f'<div class="evidence-box">Your consumption increased by <b>{change:.1f}%</b> '
            f'compared with the previous billing period.<br><br>'
            f'<b>Confidence: {confidence}%</b> '
            f'<span style="color:#8a8f98">(z-score {z_score} vs. 11-month history — higher '
            f'means further from your historical average)</span><br>'
            f'Evidence: current {current_units} units vs previous {previous_units} units.</div>',
            unsafe_allow_html=True,
        )

        st.write("")
        st.markdown("#### 🔎 Why is your bill high?")
        change_pct, contributors, contributor_sources = ai_why_bill_high(current_units, previous_units)
        st.markdown(f"**Primary reason** — ⚡ {change_pct}% increase in electricity consumption")
        st.markdown("**Likely contributors** _(retrieved from the Knowledge Center)_")
        for c in contributors:
            st.markdown(f"- {c}")
        if contributor_sources:
            st.markdown(
                "".join(f'<span class="source-chip">📚 {s}</span>' for s in set(contributor_sources)),
                unsafe_allow_html=True,
            )
        st.markdown("**💡 What you can do**")
        st.info("Reducing AC usage by approximately 1 hour/day could potentially reduce "
                 "monthly consumption by 15–20 units.")

        if any(c.get("_source_file") for c in st.session_state.custom_kb_chunks):
            st.caption("📎 Your uploaded bill's text has been indexed into the RAG "
                       "knowledge base — the AI Assistant and Recommendations page can "
                       "now ground answers in it too.")
        st.caption("👉 Head to **💡 Recommendations** for a full personalized savings plan.")
    else:
        st.caption("Upload a bill above, or click 'Use sample bill for demo' to see the analysis flow.")

# ----------------------------------------------------------------------
# PAGE: CONSUMPTION
# ----------------------------------------------------------------------

elif page == "📊 Consumption":
    st.markdown('<div class="ps-title">📊 Consumption Analytics</div>', unsafe_allow_html=True)
    st.write("")

    fig = px.bar(df, x="month", y="units", color="units", color_continuous_scale="Purples")
    fig.update_layout(height=350, margin=dict(l=10, r=10, t=10, b=10), coloraxis_showscale=False)
    st.plotly_chart(fig, use_container_width=True)

    st.caption("📊 Simulated data — this 12-month history is generated with a fixed random "
               "seed for demo purposes, not read from a real meter or utility account.")

    # The hourly curve is generated from a simple day-shape model (base load +
    # an evening AC/appliance peak) scaled by the household's own current_units,
    # instead of being a hardcoded array unrelated to any other number in the
    # app. "Peak Usage Window" is then computed FROM this curve rather than
    # being a separately hardcoded string that could silently disagree with it.
    hours = list(range(24))
    daily_avg_load = current_units / 30
    load = [
        daily_avg_load * (0.5 + 0.3 * np.sin((h - 6) / 24 * 2 * np.pi) ** 2
                           + (1.8 if 19 <= h <= 22 else 0.0))
        for h in hours
    ]
    load = [round(v, 1) for v in load]
    peak_hours = sorted(range(24), key=lambda h: load[h], reverse=True)[:4]
    peak_window = f"{min(peak_hours)}:00 – {max(peak_hours)+1}:00"
    avg_daily_cost = int(current_bill / 30)

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Consumption Trend", f"{pct_change:+.1f}%", "vs previous month")
    c2.metric("Peak Usage Window", peak_window, help="Computed from the hourly load curve below, not a fixed label.")
    c3.metric("Average Daily Cost", f"Rs. {avg_daily_cost:,}", help="Current bill ÷ 30 days.")
    c4.metric("Estimated Monthly Cost", f"Rs. {current_bill:,}")

    st.write("")
    st.markdown("#### Hourly usage pattern (modeled from your monthly units — not measured smart-meter data)")
    hfig = go.Figure(go.Scatter(x=hours, y=load, mode="lines", fill="tozeroy",
                                 line_color="#10b981"))
    hfig.update_layout(height=280, margin=dict(l=10, r=10, t=10, b=10),
                        xaxis_title="Hour of day", yaxis_title="Estimated units")
    st.plotly_chart(hfig, use_container_width=True)

# ----------------------------------------------------------------------
# PAGE: PROBLEM DETECTION
# ----------------------------------------------------------------------

elif page == "🚨 Problem Detection":
    st.markdown('<div class="ps-title">🚨 Problem Detection</div>', unsafe_allow_html=True)
    st.write("")

    avg_units = int(df["units"].iloc[:-1].mean())
    diff_pct, severity, badge_class, causes, cause_sources = ai_detect_anomaly(current_units, avg_units)

    st.markdown(f'<span class="badge {badge_class}">Severity: {severity}</span>', unsafe_allow_html=True)
    st.write("")
    st.markdown("#### Anomaly Detected: Unusual consumption spike")

    tbl = pd.DataFrame({
        "Metric": ["11-month average", "Current month", "Difference"],
        "Value": [f"{avg_units} units", f"{current_units} units", f"{diff_pct:+.1f}%"],
    })
    st.dataframe(tbl, hide_index=True, use_container_width=True)

    st.markdown("**Possible causes** _(retrieved from the Knowledge Center)_")
    for i, c in enumerate(causes, 1):
        st.markdown(f"{i}. {c}")
    if cause_sources:
        st.markdown(
            "".join(f'<span class="source-chip">📚 {s}</span>' for s in set(cause_sources)),
            unsafe_allow_html=True,
        )

    st.markdown("**Recommended action**")
    st.info("Compare your meter reading with the bill and inspect high-consumption appliances "
             "such as your AC, water heater, or any recently added equipment.")

# ----------------------------------------------------------------------
# PAGE: RECOMMENDATIONS
# ----------------------------------------------------------------------

elif page == "💡 Recommendations":
    st.markdown('<div class="ps-title">💡 Personalized Recommendations</div>', unsafe_allow_html=True)
    st.write("")

    recs = ai_recommendations(current_units)
    for r in recs:
        with st.container(border=True):
            c1, c2, c3 = st.columns([3, 1, 1])
            c1.markdown(f"**{r['title']}**")
            c2.markdown(f"Impact: {r['impact']}")
            c3.markdown(f"💰 {r['saving']}")

    total_saving = sum(int(r["saving"].split("Rs. ")[1].replace(",", "")) for r in recs)
    st.write("")
    st.success(f"Combined, these changes could save up to **Rs. {total_saving:,}/month** "
               f"(~Rs. {total_saving*12:,}/year).")

    st.divider()
    st.markdown("#### 🧠 AI-Generated Personalized Plan")
    if get_groq_client() is None:
        st.caption("💡 Add a Groq API key in Settings to generate a personalized, "
                   "LLM-written plan grounded in your bill data and (if uploaded) your "
                   "own bill PDF. Showing the calculated plan above either way.")
    else:
        st.caption("Grounded in your bill data, the Knowledge Center, and any bill/PDF "
                   "you've uploaded this session.")
        if st.button("✨ Generate AI Suggestions", type="primary"):
            with st.spinner("Asking the AI advisor..."):
                bill_for_llm = st.session_state.bill_data or ai_extract_bill(None)
                result = ai_llm_savings_suggestions(bill_for_llm, recs)
            if result:
                text, sources = result
                st.markdown(f'<div class="evidence-box">{text}</div>', unsafe_allow_html=True)
                if sources:
                    st.markdown(
                        "".join(f'<span class="source-chip">📚 {s}</span>' for s in set(sources)),
                        unsafe_allow_html=True,
                    )
            else:
                st.warning("Couldn't generate an AI plan right now — showing the calculated "
                           "plan above instead. Check your API key in Settings.")

# ----------------------------------------------------------------------
# PAGE: SAVINGS SIMULATOR
# ----------------------------------------------------------------------

elif page == "💰 Savings Simulator":
    st.markdown('<div class="ps-title">💰 What if I reduce my usage?</div>', unsafe_allow_html=True)
    st.write("")

    c1, c2 = st.columns(2)
    with c1:
        ac_now = st.slider("Current AC usage (hrs/day)", 0, 16, 8)
    with c2:
        ac_target = st.slider("Target AC usage (hrs/day)", 0, 16, 5)

    peak_shift = st.slider("% of usage shifted out of 7–11 PM peak window", 0, 100, 30)

    hrs_reduced = max(ac_now - ac_target, 0)
    units_saved_ac = hrs_reduced * 30 * 1.5  # ~1.5 kWh/hr assumption
    units_saved_peak = current_units * (peak_shift / 100) * 0.05
    total_units_saved = units_saved_ac + units_saved_peak
    bill_reduction = int(total_units_saved * RATE_PER_UNIT)
    annual_saving = bill_reduction * 12

    st.write("")
    st.markdown("#### Estimated impact")
    m1, m2, m3 = st.columns(3)
    m1.metric("Units saved", f"~{total_units_saved:.0f} kWh/month")
    m2.metric("Estimated bill reduction", f"~Rs. {bill_reduction:,}/month")
    m3.metric("Annual potential saving", f"~Rs. {annual_saving:,}")

    fig = go.Figure(go.Bar(
        x=["Current bill", "Projected bill"],
        y=[current_bill, max(current_bill - bill_reduction, 0)],
        marker_color=["#ef4444", "#10b981"],
    ))
    fig.update_layout(height=300, margin=dict(l=10, r=10, t=10, b=10), yaxis_title="Rs.")
    st.plotly_chart(fig, use_container_width=True)

# ----------------------------------------------------------------------
# PAGE: AI ASSISTANT
# ----------------------------------------------------------------------

elif page == "🤖 AI Assistant":
    st.markdown('<div class="ps-title">🤖 Ask PowerSense</div>', unsafe_allow_html=True)
    st.write("")

    if get_groq_client() is None:
        st.caption("💡 No Groq API key configured — answers are grounded in real "
                   "retrieval from the Knowledge Center, without an LLM paraphrase step. "
                   "Add a key in Settings for full generated answers.")

    quick_qs = [
        "💰 Why is my bill high?",
        "⚡ What used the most electricity?",
        "📉 How can I reduce my bill?",
        "🚨 Is there anything unusual?",
    ]
    cols = st.columns(len(quick_qs))
    clicked = None
    for col, q in zip(cols, quick_qs):
        if col.button(q, use_container_width=True):
            clicked = q

    for msg in st.session_state.chat_history:
        with st.chat_message(msg["role"]):
            if msg.get("mode"):
                chip_class = "mode-chip-llm" if msg["mode"] == "llm" else "mode-chip-retrieval"
                chip_text = "🧠 Live LLM (RAG-augmented)" if msg["mode"] == "llm" else "📚 Retrieved from Knowledge Center"
                st.markdown(f'<span class="{chip_class}">{chip_text}</span>', unsafe_allow_html=True)
            st.markdown(msg["content"])
            if msg.get("sources"):
                st.markdown(
                    "".join(f'<span class="source-chip">📚 {s}</span>' for s in msg["sources"]),
                    unsafe_allow_html=True,
                )

    user_input = st.chat_input("Ask about your bill, usage, or how to save...")
    prompt = clicked or user_input

    if prompt:
        st.session_state.chat_history.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        response, sources, mode = ai_chat_response(prompt)
        st.session_state.chat_history.append(
            {"role": "assistant", "content": response, "sources": sources, "mode": mode}
        )
        with st.chat_message("assistant"):
            chip_class = "mode-chip-llm" if mode == "llm" else "mode-chip-retrieval"
            chip_text = "🧠 Live LLM (RAG-augmented)" if mode == "llm" else "📚 Retrieved from Knowledge Center"
            st.markdown(f'<span class="{chip_class}">{chip_text}</span>', unsafe_allow_html=True)
            st.markdown(response)
            if sources:
                st.markdown(
                    "".join(f'<span class="source-chip">📚 {s}</span>' for s in sources),
                    unsafe_allow_html=True,
                )

# ----------------------------------------------------------------------
# PAGE: KNOWLEDGE CENTER (real RAG)
# ----------------------------------------------------------------------

elif page == "📚 Knowledge Center":
    st.markdown('<div class="ps-title">📚 Knowledge Center</div>'
                '<div class="ps-subtitle">Real TF-IDF retrieval over these articles + any PDFs '
                'you add — this is exactly what the AI Assistant searches</div>',
                unsafe_allow_html=True)
    st.write("")

    if not SKLEARN_AVAILABLE:
        st.warning("`scikit-learn` isn't installed, so retrieval is disabled. Run "
                   "`pip install scikit-learn` and restart.")

    _, _, all_chunks = get_rag_index()
    index_caption = f"📦 Index status: **{len(all_chunks)} chunks** indexed from {len(KNOWLEDGE_BASE)} built-in articles"
    if st.session_state.uploaded_kb_files:
        index_caption += f" + {len(st.session_state.uploaded_kb_files)} uploaded PDF(s)"
    index_caption += " · similarity method: TF-IDF cosine similarity"
    st.caption(index_caption)

    st.write("")
    st.markdown("#### 📤 Add a PDF to the knowledge base")
    kb_upload = st.file_uploader(
        "Upload a PDF (a tariff notice, your utility's FAQ, a policy doc, etc.) — it will be "
        "chunked and indexed immediately, and the AI Assistant can then cite it.",
        type=["pdf"], key="kb_pdf_uploader",
    )
    if kb_upload is not None and kb_upload.name not in st.session_state.uploaded_kb_files:
        try:
            raw_text = extract_text_from_pdf(kb_upload)
            if raw_text.strip():
                new_chunks = [
                    {"title": kb_upload.name, "category": "Uploaded", "text": c}
                    for c in _chunk_text(raw_text)
                ]
                st.session_state.custom_kb_chunks.extend(new_chunks)
                st.session_state.uploaded_kb_files.append(kb_upload.name)
                st.success(f"Indexed {len(new_chunks)} chunks from **{kb_upload.name}**.")
                st.rerun()
            else:
                st.error("Couldn't extract any text from that PDF — it may be a scanned "
                         "image (OCR isn't implemented yet).")
        except Exception as e:
            st.error(f"Couldn't read that PDF: {e}")

    if st.session_state.uploaded_kb_files:
        st.caption("Uploaded this session: " + ", ".join(st.session_state.uploaded_kb_files))

    st.write("")
    st.markdown("#### 🔎 Test retrieval")
    test_q = st.text_input("Type a question and see exactly which chunks get retrieved and how relevant they scored")
    if test_q:
        results = rag_search(test_q, k=4, min_score=0.0)
        if results:
            for r in results:
                with st.container(border=True):
                    st.markdown(f"**{r['title']}** &nbsp; · &nbsp; similarity `{r['score']}`")
                    st.caption(r["text"])
        else:
            st.info("Nothing indexed yet, or scikit-learn is unavailable.")

    st.write("")
    st.markdown("#### 📖 Built-in articles")
    categories = sorted(set(a["category"] for a in KNOWLEDGE_BASE))
    tabs = st.tabs(categories)
    for tab, cat in zip(tabs, categories):
        with tab:
            for article in [a for a in KNOWLEDGE_BASE if a["category"] == cat]:
                with st.expander(article["title"]):
                    st.write(article["content"])

    st.write("")
    st.markdown("#### AI Knowledge Source")
    st.markdown(
        '<div class="evidence-box">Responses in the AI Assistant are retrieved from this '
        'index via TF-IDF cosine similarity — each answer cites the specific chunks it '
        'actually scored highest, not a fixed source list. Questions with no good match '
        'legitimately return no sources.</div>',
        unsafe_allow_html=True,
    )

# ----------------------------------------------------------------------
# PAGE: SETTINGS
# ----------------------------------------------------------------------

elif page == "⚙️ Settings":
    st.markdown('<div class="ps-title">⚙️ Settings</div>', unsafe_allow_html=True)
    st.write("")

    st.markdown("##### Tariff")
    st.caption("This is the one setting on this page that actually changes the app's "
               "numbers — every bill, KPI, and recommendation above uses this rate.")
    new_rate = st.number_input("Rate per unit (Rs./kWh)", value=float(st.session_state.rate_per_unit),
                                step=1.0, min_value=1.0)
    if st.button("Update rate", type="primary"):
        st.session_state.rate_per_unit = new_rate
        st.rerun()

    st.divider()
    st.markdown("##### AI Assistant (optional live LLM)")
    if not GROQ_AVAILABLE:
        st.info("The `groq` package isn't installed. Run `pip install groq` to "
                "enable live LLM answers; retrieval-only answers work either way.")
    st.caption("Without a key, the AI Assistant still answers using real retrieval from the "
               "Knowledge Center — it just skips the generative model call.")
    key_input = st.text_input(
        "Groq API key", type="password",
        value=st.session_state.groq_api_key,
        help="Stored only in this browser session's memory, never written to disk. "
             "Get a free key at console.groq.com/keys.",
    )
    model_input = st.text_input("Model", value=st.session_state.llm_model,
                                 help="e.g. llama-3.3-70b-versatile, llama-3.1-8b-instant, gemma2-9b-it")
    if st.button("Save API settings"):
        st.session_state.groq_api_key = key_input
        st.session_state.llm_model = model_input or "llama-3.3-70b-versatile"
        st.success("Saved for this session.")

    if get_groq_client() is not None:
        st.caption("✅ A key is currently active (session input, GROQ_API_KEY env var, or Streamlit secrets).")
    else:
        st.caption("⚪ No active key — chat will use retrieval-only answers.")
